/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngo;

import java.util.Map;
import ngo.model.Dashboard;
import ngo.utils.GeneralUtils;

/**
 *
 * @author memoshakya
 */
public class OrganizationDetails extends javax.swing.JFrame {

    private Integer office_id;

    /**
     * Creates new form ViewOrganization
     */
    public OrganizationDetails() {
        this(-1);
        
       
        //sectorComboBox.setModel(getModelForSectorComboBox(new Dashboard().getSectors()));
    }
    
    public OrganizationDetails(int officeId) {
        initComponents();
        GeneralUtils.setUILookAndFeel(this);
        setLocationRelativeTo(null);
        setResizable(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setValues(new Dashboard().getOrganization(officeId));
        this.office_id = officeId;
        
       
    }

    public void setValues(Map<String, Object> valueMap) {
        this.orgNameTxtField.setEditable(false);
        this.addressTxtField.setEditable(false);
        this.websiteTextField.setEditable(false);
        this.emailTextField.setEditable(false);
        this.telephoneTxtField.setEditable(false);
        this.mobileTxtField.setEditable(false);
        this.chairPersonTxtField.setEditable(false);
        this.hodTxtField.setEditable(false);
        this.sectorTextField.setEditable(false);
        
        String officeName = valueMap.containsKey("officeName") ? valueMap.get("officeName").toString() : "";
        String address = valueMap.containsKey("address") ? valueMap.get("address").toString() : "";
        String website = valueMap.containsKey("website") ? valueMap.get("website").toString() : "";
        String email = valueMap.containsKey("email") ? valueMap.get("email").toString() : "";
        String telNo = valueMap.containsKey("telephone_no") ? valueMap.get("telephone_no").toString() : "";
        String mobNo = valueMap.containsKey("mobile_number") ? valueMap.get("mobile_number").toString() : "";
        String chairPerson = valueMap.containsKey("chair_person") ? valueMap.get("chair_person").toString() : "";
        String headOfOrg = valueMap.containsKey("head_of_org") ? valueMap.get("head_of_org").toString() : "";
        String sectorName = valueMap.containsKey("sector_name") ? valueMap.get("sector_name").toString() : "";
                
        setTitle("Organization Details: "+ officeName);
        
        
        this.orgNameTxtField.setText(officeName);
        this.addressTxtField.setText(address);
        this.websiteTextField.setText(website);
        this.emailTextField.setText(email);
        this.telephoneTxtField.setText(telNo);
        this.mobileTxtField.setText(mobNo);
        this.chairPersonTxtField.setText(chairPerson);
        this.hodTxtField.setText(headOfOrg);
        this.sectorTextField.setText(sectorName);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orgNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        websiteNameLabel = new javax.swing.JLabel();
        mobileNumberLabel = new javax.swing.JLabel();
        emailAddLabel = new javax.swing.JLabel();
        chairPersonLabel = new javax.swing.JLabel();
        hodLabel = new javax.swing.JLabel();
        orgNameTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        telephoneTxtField = new javax.swing.JTextField();
        mobileTxtField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        websiteTextField = new javax.swing.JTextField();
        chairPersonTxtField = new javax.swing.JTextField();
        hodTxtField = new javax.swing.JTextField();
        telephoneNoLabel = new javax.swing.JLabel();
        sectorLabel = new javax.swing.JLabel();
        asterisk2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        sectorTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        closeMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Organization Details"));

        orgNameLabel.setText("Organization's Name");

        addressLabel.setText("Address");
        addressLabel.setToolTipText("");

        websiteNameLabel.setText("Website");

        mobileNumberLabel.setText("Mobile Number");

        emailAddLabel.setText("Email Address");

        chairPersonLabel.setText("Chair Person");

        hodLabel.setText("Head of Organization");

        orgNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgNameTxtFieldActionPerformed(evt);
            }
        });

        telephoneNoLabel.setText("Telephone Number");

        sectorLabel.setText("Sector");

        asterisk2.setForeground(new java.awt.Color(246, 9, 9));

        Delete.setText("Delete");
        Delete.setToolTipText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Edit");
        Update.setToolTipText("Edit");
        Update.setSelected(true);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orgNameLabel)
                            .addComponent(addressLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(telephoneNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asterisk2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chairPersonLabel)
                            .addComponent(mobileNumberLabel)
                            .addComponent(emailAddLabel)
                            .addComponent(websiteNameLabel)
                            .addComponent(sectorLabel)
                            .addComponent(hodLabel))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                            .addComponent(mobileTxtField)
                            .addComponent(emailTextField)
                            .addComponent(websiteTextField)
                            .addComponent(chairPersonTxtField)
                            .addComponent(hodTxtField)
                            .addComponent(orgNameTxtField)
                            .addComponent(addressTxtField)
                            .addComponent(sectorTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgNameLabel)
                    .addComponent(orgNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneNoLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileNumberLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(websiteNameLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairPersonTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairPersonLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hodTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hodLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectorLabel)
                    .addComponent(sectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(asterisk2)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        closeMenu.setText("Close");
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        AddOrganization addOrganization = new AddOrganization();
        addOrganization.setVisible(true);
        addOrganization.setValues(new Dashboard().getOrganization(this.office_id));
        this.dispose();
    }//GEN-LAST:event_UpdateActionPerformed

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeMenuActionPerformed

    private void orgNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgNameTxtFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel asterisk2;
    private javax.swing.JLabel chairPersonLabel;
    private javax.swing.JTextField chairPersonTxtField;
    private javax.swing.JMenuItem closeMenu;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel hodLabel;
    private javax.swing.JTextField hodTxtField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mobileNumberLabel;
    private javax.swing.JTextField mobileTxtField;
    private javax.swing.JLabel orgNameLabel;
    private javax.swing.JTextField orgNameTxtField;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JTextField sectorTextField;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JTextField telephoneTxtField;
    private javax.swing.JLabel websiteNameLabel;
    private javax.swing.JTextField websiteTextField;
    // End of variables declaration//GEN-END:variables
}
