/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngo;

import java.util.Map;
import javax.swing.JOptionPane;
import ngo.model.Dashboard;
import ngo.model.Organization;
import ngo.utils.GeneralUtils;
import ngo.utils.Message;

/**
 *
 * @author memoshakya
 */
public class OrganizationDetails extends javax.swing.JFrame {

    private Integer office_id;

    /**
     * Creates new form ViewOrganization
     */
    public OrganizationDetails() {
        this(-1);

        //sectorComboBox.setModel(getModelForSectorComboBox(new Dashboard().getSectors()));
    }

    public OrganizationDetails(int officeId) {
        initComponents();
        GeneralUtils.setUILookAndFeel(this);
        setLocationRelativeTo(null);
        setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setValues(new Organization(officeId));
        this.office_id = officeId;

    }

    public void setValues(Organization orgDetails) {
        this.orgNameTxtField.setEditable(false);
        this.addressTxtField.setEditable(false);
        this.websiteTextField.setEditable(false);
        this.emailTextField.setEditable(false);
        this.telephoneTxtField.setEditable(false);
        this.mobileTxtField.setEditable(false);
        this.chairPersonTxtField.setEditable(false);
        this.hodTxtField.setEditable(false);
        this.sectorTextField.setEditable(false);

        setTitle("Organization Details: " + orgDetails.getOfficeName());

        this.orgNameTxtField.setText(orgDetails.getOfficeName());
        this.addressTxtField.setText(orgDetails.getAddress());
        this.websiteTextField.setText(orgDetails.getWebsite());
        this.emailTextField.setText(orgDetails.getEmail());
        this.telephoneTxtField.setText(orgDetails.getTelephoneNo());
        this.mobileTxtField.setText(orgDetails.getMobileNo());
        this.chairPersonTxtField.setText(orgDetails.getChairPerson());
        this.hodTxtField.setText(orgDetails.getHeadOfOrg());
        this.sectorTextField.setText(orgDetails.getSectorName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orgNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        websiteNameLabel = new javax.swing.JLabel();
        mobileNumberLabel = new javax.swing.JLabel();
        emailAddLabel = new javax.swing.JLabel();
        chairPersonLabel = new javax.swing.JLabel();
        hodLabel = new javax.swing.JLabel();
        orgNameTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        telephoneTxtField = new javax.swing.JTextField();
        mobileTxtField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        websiteTextField = new javax.swing.JTextField();
        chairPersonTxtField = new javax.swing.JTextField();
        hodTxtField = new javax.swing.JTextField();
        telephoneNoLabel = new javax.swing.JLabel();
        sectorLabel = new javax.swing.JLabel();
        asterisk2 = new javax.swing.JLabel();
        sectorTextField = new javax.swing.JTextField();
        additionalDetailsButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        closeMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        editMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Organization Details"));

        orgNameLabel.setText("Organization's Name");

        addressLabel.setText("Address");
        addressLabel.setToolTipText("");

        websiteNameLabel.setText("Website");

        mobileNumberLabel.setText("Mobile Number");

        emailAddLabel.setText("Email Address");

        chairPersonLabel.setText("Chair Person");

        hodLabel.setText("Head of Organization");

        orgNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgNameTxtFieldActionPerformed(evt);
            }
        });

        telephoneNoLabel.setText("Telephone Number");

        sectorLabel.setText("Sector");

        asterisk2.setForeground(new java.awt.Color(246, 9, 9));

        additionalDetailsButton.setText("Additional Details");
        additionalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionalDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orgNameLabel)
                            .addComponent(addressLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(telephoneNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asterisk2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chairPersonLabel)
                            .addComponent(mobileNumberLabel)
                            .addComponent(emailAddLabel)
                            .addComponent(websiteNameLabel)
                            .addComponent(sectorLabel)
                            .addComponent(hodLabel))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                            .addComponent(mobileTxtField)
                            .addComponent(emailTextField)
                            .addComponent(websiteTextField)
                            .addComponent(chairPersonTxtField)
                            .addComponent(hodTxtField)
                            .addComponent(orgNameTxtField)
                            .addComponent(addressTxtField)
                            .addComponent(sectorTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(additionalDetailsButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(additionalDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgNameLabel)
                    .addComponent(orgNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneNoLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileNumberLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(websiteNameLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairPersonTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairPersonLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hodTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hodLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectorLabel)
                    .addComponent(sectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(asterisk2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        closeMenu.setText("Close");
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        editMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        editMenuItem.setText("Edit");
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(editMenuItem);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(deleteMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeMenuActionPerformed

    private void orgNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgNameTxtFieldActionPerformed

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        AddOrganization addOrganization = new AddOrganization();
        addOrganization.setVisible(true);
        addOrganization.setValues(new Organization(this.office_id));
        this.dispose();
    }//GEN-LAST:event_editMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        String message = "All the information for this organization will be deleted. \nAre you sure you want to delete?";
        int answer = JOptionPane.showConfirmDialog(this, message, "Delete Organization", 0);

        if (answer == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Message deleteMessage = Organization.deleteOrganization(this.office_id);
            JOptionPane.showMessageDialog(this,
                    deleteMessage.getMessage(),
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void additionalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionalDetailsButtonActionPerformed
        QuestionsForm form = new QuestionsForm(office_id, QuestionsForm.Type.VIEW);
        form.setVisible(true);
    }//GEN-LAST:event_additionalDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionalDetailsButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel asterisk2;
    private javax.swing.JLabel chairPersonLabel;
    private javax.swing.JTextField chairPersonTxtField;
    private javax.swing.JMenuItem closeMenu;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem editMenuItem;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel hodLabel;
    private javax.swing.JTextField hodTxtField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mobileNumberLabel;
    private javax.swing.JTextField mobileTxtField;
    private javax.swing.JLabel orgNameLabel;
    private javax.swing.JTextField orgNameTxtField;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JTextField sectorTextField;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JTextField telephoneTxtField;
    private javax.swing.JLabel websiteNameLabel;
    private javax.swing.JTextField websiteTextField;
    // End of variables declaration//GEN-END:variables
}
