/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngo;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextArea;

/**
 *
 * @author swshrestha
 */
public class QuestionsForm extends JFrame {

    /**
     * Creates new form TableTest
     */
    public QuestionsForm() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel2.setText("jLabel1");

        jScrollPane2.setViewportView(jEditorPane2);

        String[] questionArray = {
            "1. I have something to say, it's beter to burn out then to fade away. "
            + "This is a very long String to see if you can wrap with in "
            + "the available spaceI have something to say, it's beter to burn out then to fade away."
            + " This is a very long String to see if you can wrap with in",
            "2. I have something to say, it's beter to burn out then to fade away. "
            + "This is a very long String to see if you can wrap with in "
            + "the available spaceI have something to say, it's beter to burn out then to fade away."
            + " This is a very long String to see if you can wrap with in",
            "3. I have something to say, it's beter to burn out then to fade away. "
            + "This is a very long String to see if you can wrap with in "
            + "the available spaceI have something to say, it's beter to burn out then to fade away."
            + " This is a very long String to see if you can wrap with in",
            "4. I have something to say, it's beter to burn out then to fade away. "
            + "This is a very long String to see if you can wrap with in "
            + "the available spaceI have something to say, it's beter to burn out then to fade away."
            + " This is a very long String to see if you can wrap with in",
            "5. I have something to say, it's beter to burn out then to fade away. "
            + "This is a very long String to see if you can wrap with in "
            + "the available spaceI have something to say, it's beter to burn out then to fade away."
            + " This is a very long String to see if you can wrap with in"};

        JLabel[] labelArray = new JLabel[questionArray.length];
        JTextArea[] textAreaArray = new JTextArea[questionArray.length];
        JSeparator[] seperatorArray = new JSeparator[questionArray.length];

        populateLabels(labelArray, questionArray, textAreaArray, seperatorArray);

        jLabel1.setText("JLABEL !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        GroupLayout.Group horizontalGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.Group verticalGroup = layout.createSequentialGroup().addContainerGap();

        populateGroups(horizontalGroup, labelArray, textAreaArray, seperatorArray);
        populateGroupsVertical(verticalGroup, labelArray, textAreaArray, seperatorArray);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(horizontalGroup)
            ));
                        
                        

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(verticalGroup));
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(372, 372, 372)
//                        .addComponent(jSeparator1))
//                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(jScrollPane2)
//                    .addComponent(jSeparator2))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(7, 7, 7)
//                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(1, 1, 1)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(2, 2, 2)
//                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(82, Short.MAX_VALUE))
//        );
        pack();
    }// </editor-fold>          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration                 

    private void populateLabels(JLabel[] labelArray, String[] questionArray, JTextArea[] textAreaArray,JSeparator[] seperatorArray) {

        for (int i = 0; i < questionArray.length; i++) {

            labelArray[i] = new JLabel(getHtmlQuotes(questionArray[i]));
            textAreaArray[i] = new JTextArea();
            seperatorArray[i] = new JSeparator(0);
        }

    }

    private String getHtmlQuotes(String inputText) {
        StringBuilder sb = new StringBuilder();
        sb.append("<html>").append(inputText).append("</html>");
        return sb.toString();
    }

    private void populateGroups(GroupLayout.Group group, JLabel[] labelArray, JTextArea[] textAreaArray, JSeparator[] seperatorArray) {
        for (int i = 0; i < labelArray.length; i++) {
            ((GroupLayout.ParallelGroup) group).addComponent(labelArray[i], javax.swing.GroupLayout.Alignment.TRAILING,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
            ((GroupLayout.ParallelGroup) group).addComponent(textAreaArray[i], javax.swing.GroupLayout.Alignment.TRAILING,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
            ((GroupLayout.ParallelGroup) group).addComponent(seperatorArray[i], javax.swing.GroupLayout.Alignment.TRAILING,  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
//            group.addComponent(labelArray[i],  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
//            group.addComponent(textAreaArray[i], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        }

    }

    private void populateGroupsVertical(GroupLayout.Group group, JLabel[] labelArray, JTextArea[] textAreaArray, JSeparator[] seperatorArray) {
        for (int i = 0; i < labelArray.length; i++) {
            group.addComponent(labelArray[i],  javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
            group.addComponent(textAreaArray[i], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
            group.addComponent(seperatorArray[i], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        }

    }

   

}
